import type { Post } from './lib/types';

export const MOCK_POSTS: Post[] = [
  {
    id: '0',
    timestamp: 1723791475000,
    author: '0://bob',
    nickname: 'Bob',
    text: "Just finished reading an amazing book! 📚✨ It's called 'The Alchemist' by Paulo Coelho. Highly recommend it to anyone looking for a bit of inspiration and magic in their life. Has anyone else read it? What did you think?",
  },
  {
    id: '1',
    timestamp: 1723791575000,
    author: '0://alice',
    nickname: 'Alice',
    text: 'Had a great time hiking today! The view from the top was breathtaking. 🏞️',
  },
  {
    id: '2',
    timestamp: 1723791675000,
    author: '0://charlie',
    nickname: 'Charlie',
    text: 'Just baked some cookies and they turned out delicious! 🍪 Who wants some?',
  },
  {
    id: '3',
    timestamp: 1723791775000,
    author: '0://dave',
    nickname: 'Dave',
    text: 'Watching the sunset by the beach. Life is good. 🌅',
  },
  {
    id: '4',
    timestamp: 1723791875000,
    author: '0://eve',
    nickname: 'Eve',
    text: "Started learning how to play the guitar today. My fingers hurt but it's so much fun! 🎸",
  },
  {
    id: '5',
    timestamp: 1723791975000,
    author: '0://frank',
    nickname: 'Frank',
    text: 'Just finished a 5K run. Feeling accomplished and exhausted at the same time. 🏃‍♂️',
  },
  {
    id: '6',
    timestamp: 1723792075000,
    author: '0://grace',
    nickname: 'Grace',
    text: 'Made a new friend at the dog park today. Both our dogs got along so well! 🐶',
  },
  {
    id: '7',
    timestamp: 1723792175000,
    author: '0://heidi',
    nickname: 'Heidi',
    text: 'Trying out a new recipe tonight. Hope it turns out as good as it looks in the picture! 🍲',
  },
  {
    id: '8',
    timestamp: 1723792275000,
    author: '0://ivan',
    nickname: 'Ivan',
    text: 'Just got back from a weekend getaway. Feeling refreshed and ready to tackle the week ahead. 🏖️',
  },
  {
    id: '9',
    timestamp: 1723792375000,
    author: '0://judy',
    nickname: 'Judy',
    text: "Spent the afternoon painting. It's so relaxing and therapeutic. 🎨",
  },
  {
    id: '10',
    timestamp: 1723792475000,
    author: '0://ken',
    nickname: 'Ken',
    text: 'Just watched an amazing movie. Highly recommend it to everyone! 🎬',
  },
];
