name: 'Common Setup'

description: 'Setup nodejs and cache'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Get node version
      id: node
      shell: bash
      run: echo "version=$(node -v)" >> $GITHUB_OUTPUT

    # rebuild the cache if OS, package-lock.json or node version changes
    - name: Get node_modules cache
      uses: actions/cache@v4
      id: node_modules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
