name: Common Setup

on:
  workflow_run:
    workflows: ['Deploy Development', 'run-build', 'run-lint', 'run-tests', 'run-typecheck']
    types:
      - requested

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get node version
        id: node
        run: echo "version=$(node -v)" >> $GITHUB_OUTPUT

      # rebuild the cache if OS, package-lock.json or node version changes
      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
