name: Create Tag
on:
  push:
    branches:
      - main
      - 'hotfix/**'
    paths:
      - package.json
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: '${{ secrets.COMMIT_KEY }}'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: ./.github/create-tag
