name: 'Create Release'
on:
  push:
    tags:
      - '**'

jobs:
  create_release:
    name: 'Create Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Determine tag'
        run: 'echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV'

      - name: 'Create release'
        uses: 'actions/github-script@v5'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: true,
                generate_release_notes: true,
                name: "Release ${{process.env.RELEASE_TAG}}",
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
