name: run-build
on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_INFURA_URL: ${{secrets.INFURA_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' >> .npmrc
      - run: npm install
      - name: Build project
        run: npm run build
