name: run-tests-vitest
on:
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      REACT_APP_INFURA_URL: ${{secrets.INFURA_URL}}
    steps:
      - uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common

      - run: echo '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' >> .npmrc
      - run: npm install --legacy-peer-deps
      - run: npm run test:vitest
