name: Test

on: workflow_call

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common
      - run: npm run test:vitest

  jest:
    name: Jest (legacy tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common
      - run: npm run test
